# Generated by Django 3.2.8 on 2021-11-13 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('user_agent', models.TextField(default='', max_length=100)),
                ('ip', models.TextField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='IP地址')),
                ('geo_country', models.TextField(default='', max_length=100, verbose_name='国家')),
                ('geo_subdivision', models.TextField(default='', max_length=100, verbose_name='省份')),
                ('geo_city', models.TextField(default='', max_length=100, verbose_name='城市')),
                ('longtitude', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='纬度')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=500)),
                ('visit_date', models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 10, 787557))),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.TextField(default='', max_length=500)),
                ('first_income_date', models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 10, 788128))),
                ('last_income_date', models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 10, 788152))),
                ('location_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to='geolocation.geolocation')),
                ('visit_path', models.ManyToManyField(related_name='visitrouter', to='geolocation.VisitRouter')),
            ],
        ),
    ]
