# Generated by Django 3.2.8 on 2021-10-21 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(default='', max_length=100)),
                ('ip', models.TextField(default='', max_length=100)),
                ('geo_country', models.TextField(default='', max_length=100)),
                ('geo_subdivision', models.TextField(default='', max_length=100)),
                ('geo_city', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=500)),
                ('visit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(default='', max_length=500)),
                ('first_income_date', models.DateTimeField(auto_now=True)),
                ('last_income_date', models.DateTimeField(auto_now=True)),
                ('location_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to='geolocation.geolocation', verbose_name='detail info')),
                ('visit_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitrouter', to='geolocation.visitrouter')),
            ],
        ),
    ]
