# Generated by Django 3.2.8 on 2021-10-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisitor',
            old_name='session_id',
            new_name='session_uuid',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.TextField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='sitevisitor',
            name='visit_path',
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='visit_path',
            field=models.ManyToManyField(related_name='visitrouter', to='geolocation.VisitRouter'),
        ),
    ]
