# Generated by Django 3.2.8 on 2021-11-13 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitor',
            name='first_income_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 15, 816267)),
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='last_income_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 15, 816281)),
        ),
        migrations.AlterField(
            model_name='visitrouter',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 19, 17, 15, 816022)),
        ),
    ]
