# Generated by Django 3.2.8 on 2021-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20211023_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='geo_city',
            field=models.TextField(default='', max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='geo_country',
            field=models.TextField(default='', max_length=100, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='geo_subdivision',
            field=models.TextField(default='', max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='ip',
            field=models.TextField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='IP地址'),
        ),
    ]
